# Generated by Django 3.2.7 on 2021-10-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
    ]
